### ISSUE TITLE
Egoboo's Massive Copyright Infringement Record

### ISSUE THREAD

**Issue by saniv** [egoboo/egoboo-assets#1]
Most of Egoboo's sound samples are stolen
I.e. from Baldur's Gate:
https://raw.githubusercontent.com/egoboo/egoboo-assets/master/basicdat/stealth.ogg
from the soundtrack to Indiana Jones movie
https://github.com/egoboo/egoboo-assets/blob/master/modules/archaeologist.mod/objects/bouldertrap.obj/sound2.wav

A lot of others Egoboo sounds appear to be coming from Sound Ideas.

**Comment by michaelheilmann** [comment]
If you have means to investigate this, can you add your findings to this bug.
I am no sure what else is "slumbering" in Egoboo's depths, information on that is appreciated.

**Comment by michaelheilmann** [comment]
I am not sure about the Sound Ideas sounds.
If they at all originate from Sound Ideas, it'd be interesting wether or not this a problem.
I guess that 
https://github.com/egoboo/egoboo-assets/blob/master/modules/archaeologist.mod/objects/bouldertrap.obj/sound2.wav
originates from the Indiana Jones motion picture soundtrack is - well - obvious.
I guess we have to find a way to replace them. However, there is another issue. The dead Egoboo SourceForge repository might contain them as well. I am not sure who to contact regarding this.

**Comment by michaelheilmann** [comment]
https://raw.githubusercontent.com/egoboo/egoboo-assets/master/basicdat/stealth.ogg
wether or not this file originates from Baldur's Gate I can't tell. I require a full list with proofs as i do not destroy other's people work without good reason. I guess I would then ask the respective copyright holders for permission and then take action.
