### ISSUE TITLE
Remove possibly copyrighted sound

### ISSUE THREAD

**Issue by michaelheilmann** [egoboo/egoboo-assets#2]
https://github.com/egoboo/egoboo-assets/blob/master/modules/archaeologist.mod/objects/bouldertrap.obj/sound2.wav
seems like a direct rip from the Indiana Jones motion picture soundtrack.
It should be replaced by some similar sounding sound with appropriate license terms.

**Comment by Zefz** [comment]
I vote to close this as non-issue because this goes under the "fair use" law for parody or satirical effect. This could in perhaps be a bigger issue if Egoboo was not a non-profit (i.e commercial) service.

https://en.wikisource.org/wiki/United_States_Code/Title_17/Chapter_10/Sections_1008_and_1009
> The U.S. Supreme Court described fair use as an affirmative defense in Campbell v. Acuff-Rose Music, Inc.[6] This means that in litigation on copyright infringement, the defendant bears the burden of raising and proving that the use was fair and not an infringement. Thus, fair use need not even be raised as a defense unless the plaintiff first shows (or the defendant concedes) a "prima facie" case of copyright infringement. If the work was not copyrightable, the term had expired, **or the defendant's work borrowed only a small amount**, for instance, then the plaintiff cannot make out a prima facie case of infringement, and the defendant need not even raise the fair use defense.

**Comment by michaelheilmann** [comment]
Sounds reasonable. Closed.
